"""
Property-based test for report completeness.

**Feature: research-ai-assistant, Property 9: Report Completeness**
**Validates: Requirements 7.2, 7.3, 7.4**

Property 9: Report Completeness
*For any* final report generated by the Reasoning_Chain, it SHALL contain
all four required sections: summary, key_points (as a list), comparison,
and citations.
"""

import pytest
from hypothesis import given, strategies as st, settings, HealthCheck

from models import FinalReport, Citation, SourceSummary


# Strategy to generate non-empty strings for report content
non_empty_text_strategy = st.text(
    alphabet=st.characters(whitelist_categories=('L', 'N', 'P', 'S', 'Z')),
    min_size=10,
    max_size=500
).filter(lambda x: x.strip())


# Strategy to generate valid citations
citation_strategy = st.builds(
    Citation,
    number=st.integers(min_value=1, max_value=100),
    title=st.text(min_size=1, max_size=100).filter(lambda x: x.strip()),
    url=st.from_regex(r'https?://[a-z]+\.[a-z]{2,3}(/[a-z0-9]+)*', fullmatch=True)
)


# Strategy to generate a list of citations (at least 1)
citations_list_strategy = st.lists(
    citation_strategy,
    min_size=1,
    max_size=10
)


# Strategy to generate key points (list of non-empty strings)
key_points_strategy = st.lists(
    non_empty_text_strategy,
    min_size=1,
    max_size=10
)


# Strategy to generate language codes
language_strategy = st.sampled_from(["en", "fa"])


@given(
    summary=non_empty_text_strategy,
    key_points=key_points_strategy,
    comparison=non_empty_text_strategy,
    citations=citations_list_strategy,
    language=language_strategy
)
@settings(max_examples=100, suppress_health_check=[HealthCheck.too_slow], deadline=None)
def test_property_report_has_all_required_sections(
    summary: str,
    key_points: list,
    comparison: str,
    citations: list,
    language: str
):
    """
    **Feature: research-ai-assistant, Property 9: Report Completeness**
    **Validates: Requirements 7.2, 7.3, 7.4**
    
    For any FinalReport, it SHALL contain all four required sections:
    summary, key_points (as a list), comparison, and citations.
    """
    # Create a FinalReport with all sections
    report = FinalReport(
        summary=summary,
        key_points=key_points,
        comparison=comparison,
        citations=citations,
        language=language
    )
    
    # Verify summary section exists and is non-empty (Requirement 7.2)
    assert hasattr(report, 'summary'), "Report must have a 'summary' attribute"
    assert report.summary is not None, "Report summary must not be None"
    assert isinstance(report.summary, str), "Report summary must be a string"
    assert len(report.summary.strip()) > 0, "Report summary must not be empty"
    
    # Verify key_points section exists and is a non-empty list (Requirement 7.3)
    assert hasattr(report, 'key_points'), "Report must have a 'key_points' attribute"
    assert report.key_points is not None, "Report key_points must not be None"
    assert isinstance(report.key_points, list), "Report key_points must be a list"
    assert len(report.key_points) > 0, "Report key_points must not be empty"
    
    # Verify each key point is a non-empty string
    for i, point in enumerate(report.key_points):
        assert isinstance(point, str), f"Key point {i+1} must be a string"
        assert len(point.strip()) > 0, f"Key point {i+1} must not be empty"
    
    # Verify comparison section exists and is non-empty (Requirement 7.4)
    assert hasattr(report, 'comparison'), "Report must have a 'comparison' attribute"
    assert report.comparison is not None, "Report comparison must not be None"
    assert isinstance(report.comparison, str), "Report comparison must be a string"
    assert len(report.comparison.strip()) > 0, "Report comparison must not be empty"
    
    # Verify citations section exists and is a non-empty list
    assert hasattr(report, 'citations'), "Report must have a 'citations' attribute"
    assert report.citations is not None, "Report citations must not be None"
    assert isinstance(report.citations, list), "Report citations must be a list"
    assert len(report.citations) > 0, "Report citations must not be empty"


@given(
    num_key_points=st.integers(min_value=1, max_value=15),
    num_citations=st.integers(min_value=1, max_value=10)
)
@settings(max_examples=100, suppress_health_check=[HealthCheck.too_slow], deadline=None)
def test_property_report_preserves_key_points_count(
    num_key_points: int,
    num_citations: int
):
    """
    **Feature: research-ai-assistant, Property 9: Report Completeness**
    **Validates: Requirements 7.3**
    
    For any FinalReport with N key points, the key_points list SHALL
    contain exactly N items.
    """
    # Generate key points
    key_points = [f"Key point number {i+1} about the research topic" for i in range(num_key_points)]
    
    # Generate citations
    citations = [
        Citation(number=i+1, title=f"Source {i+1}", url=f"https://example{i+1}.com")
        for i in range(num_citations)
    ]
    
    # Create report
    report = FinalReport(
        summary="This is a comprehensive summary of the research findings.",
        key_points=key_points,
        comparison="This section compares the different sources.",
        citations=citations,
        language="en"
    )
    
    # Verify key points count is preserved
    assert len(report.key_points) == num_key_points, (
        f"Report should have exactly {num_key_points} key points, "
        f"but has {len(report.key_points)}"
    )
    
    # Verify citations count is preserved
    assert len(report.citations) == num_citations, (
        f"Report should have exactly {num_citations} citations, "
        f"but has {len(report.citations)}"
    )


@given(
    summary_text=non_empty_text_strategy,
    comparison_text=non_empty_text_strategy
)
@settings(max_examples=100, suppress_health_check=[HealthCheck.too_slow], deadline=None)
def test_property_report_content_integrity(
    summary_text: str,
    comparison_text: str
):
    """
    **Feature: research-ai-assistant, Property 9: Report Completeness**
    **Validates: Requirements 7.2, 7.4**
    
    For any FinalReport, the summary and comparison content SHALL be
    preserved exactly as provided.
    """
    key_points = ["Point 1", "Point 2", "Point 3"]
    citations = [Citation(number=1, title="Test", url="https://test.com")]
    
    report = FinalReport(
        summary=summary_text,
        key_points=key_points,
        comparison=comparison_text,
        citations=citations,
        language="en"
    )
    
    # Verify content is preserved exactly
    assert report.summary == summary_text, (
        f"Summary content should be preserved. "
        f"Expected: '{summary_text}', Got: '{report.summary}'"
    )
    
    assert report.comparison == comparison_text, (
        f"Comparison content should be preserved. "
        f"Expected: '{comparison_text}', Got: '{report.comparison}'"
    )


@given(
    key_points=st.lists(
        st.text(min_size=5, max_size=100).filter(lambda x: x.strip()),
        min_size=3,
        max_size=10
    )
)
@settings(max_examples=100, suppress_health_check=[HealthCheck.too_slow], deadline=None)
def test_property_key_points_are_list_type(key_points: list):
    """
    **Feature: research-ai-assistant, Property 9: Report Completeness**
    **Validates: Requirements 7.3**
    
    For any FinalReport, the key_points section SHALL be a list type,
    not a string or other type.
    """
    report = FinalReport(
        summary="Test summary",
        key_points=key_points,
        comparison="Test comparison",
        citations=[Citation(number=1, title="Test", url="https://test.com")],
        language="en"
    )
    
    # Verify key_points is specifically a list type
    assert type(report.key_points) is list, (
        f"key_points must be a list type, got {type(report.key_points)}"
    )
    
    # Verify each item in key_points is a string
    for i, point in enumerate(report.key_points):
        assert type(point) is str, (
            f"Each key point must be a string, "
            f"but key_points[{i}] is {type(point)}"
        )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
